// ? Fichier utilisé pour les svg de technos.
// ? Utilisé dans <Select />

export const technosPath = {
  java: '/images/technos/java.svg',
  html: '/images/technos/html.svg',
  css: '/images/technos/css.svg',
  javascript: '/images/technos/javascript.svg',
  react: '/images/technos/react.svg',
  sql: '/images/technos/sql.svg',
  python: '/images/technos/python.svg',
  c: '/images/technos/c.svg',
  // cplusplus: '/images/technos/c++.svg',
  php: '/images/technos/php.svg',
  // go: '/images/technos/go.svg',
  // jest: '/images/technos/jest.svg',
  // joy: '/images/technos/joi.svg',
  // cobol: '/images/technos/cobol.svg',
  graphql: '/images/technos/graphql.svg',
  // faker: '/images/technos/faker.svg',
  typescript: '/images/technos/typescript.svg',
  bootstrap: '/images/technos/bootstrap.svg',
  angular: '/images/technos/angular.svg',
  // rest: '/images/technos/rust.svg',
  // ejs: '/images/technos/ejs.svg',
  github: '/images/technos/github.svg',
  insomnia: '/images/technos/insomnia.svg',
  nodejs: '/images/technos/nodejs.svg',
  postgresql: '/images/technos/postgresql.svg',
  redux: '/images/technos/redux.svg',
  sequelize: '/images/technos/sequelize.svg',
  strapi: '/images/technos/strapi.svg',
  vite: '/images/technos/vite.svg',
  vuejs: '/images/technos/vuejs.svg',
};

export const technos = [
  {
    id: 'java',
    label: 'Java',
    name: 'Java',
    value: 'Java',
    path: technosPath.java,
  },
  {
    id: 'html',

    label: 'Html',
    name: 'Html',
    value: 'Html',
    path: technosPath.html,
  },
  {
    id: 'css',
    label: 'Css',
    name: 'Css',
    value: 'Css',
    path: technosPath.css,
  },
  {
    id: 'javascript',
    label: 'Javascript',
    name: 'Javascript',
    value: 'Javascript',
    path: technosPath.javascript,
  },
  {
    id: 'react',
    label: 'React',
    name: 'React',
    value: 'React',
    path: technosPath.react,
  },
  {
    id: 'sql',
    label: 'Sql',
    name: 'Sql',
    value: 'Sql',
    path: technosPath.sql,
  },
  {
    id: 'python',
    label: 'Python',
    name: 'Python',
    value: 'Python',
    path: technosPath.python,
  },
  {
    id: 'c',
    label: 'C',
    name: 'C',
    value: 'C',
    path: technosPath.c,
  },
  // {
  //   id: 'c++',
  //   label: 'C++',
  //   name: 'C++',
  //   value: 'C++',
  //   path: technosPath.cplusplus,
  // },
  {
    id: 'php',
    label: 'Php',
    name: 'Php',
    value: 'Php',
    path: technosPath.php,
  },
  // {
  //   id: 'go',
  //   label: 'Go',
  //   name: 'Go',
  //   value: 'Go',
  //   path: technosPath.go,
  // },
  // {
  //   id: 'jest',
  //   label: 'Jest',
  //   name: 'Jest',
  //   value: 'Jest',
  //   path: technosPath.jest,
  // },
  // {
  //   id: 'joi',
  //   label: 'Joi',
  //   name: 'Joi',
  //   value: 'Joi',
  //   path: technosPath.joy,
  // },
  // {
  //   id: 'cobol',
  //   label: 'Cobol',
  //   name: 'Cobol',
  //   value: 'Cobol',
  //   path: technosPath.cobol,
  // },
  // {
  //   id: 'faker',
  //   label: 'Faker',
  //   name: 'Faker',
  //   value: 'Faker',
  //   path: technosPath.faker,
  // },
  {
    id: 'graphql',
    label: 'Graphql',
    name: 'Graphql',
    value: 'Graphql',
    path: technosPath.graphql,
  },
  {
    id: 'typescript',
    label: 'Typescript',
    name: 'Typescript',
    value: 'Typescript',
    path: technosPath.typescript,
  },
  {
    id: 'bootstrap',
    label: 'Bootstrap',
    name: 'Bootstrap',
    value: 'Bootstrap',
    path: technosPath.bootstrap,
  },
  {
    id: 'angular',
    label: 'Angular',
    name: 'Angular',
    value: 'Angular',
    path: technosPath.angular,
  },
  // {
  //   id: 'rust',
  //   label: 'Rust',
  //   name: 'Rust',
  //   value: 'Rust',
  //   path: technosPath.rest,
  // },
  // {
  //   id: 'ejs',
  //   label: 'Ejs',
  //   name: 'Ejs',
  //   value: 'Ejs',
  //   path: technosPath.ejs,
  // },
  {
    id: 'github',
    label: 'Github',
    name: 'Github',
    value: 'Github',
    path: technosPath.github,
  },
  {
    id: 'insomnia',
    label: 'Insomnia',
    name: 'Insomnia',
    value: 'Insomnia',
    path: technosPath.insomnia,
  },
  {
    id: 'nodejs',
    label: 'Nodejs',
    name: 'Nodejs',
    value: 'Nodejs',
    path: technosPath.nodejs,
  },
  {
    id: 'postgresql',
    label: 'Postgresql',
    name: 'Postgresql',
    value: 'Postgresql',
    path: technosPath.postgresql,
  },
  {
    id: 'redux',
    label: 'Redux',
    name: 'Redux',
    value: 'Redux',
    path: technosPath.redux,
  },
  {
    id: 'sequelize',
    label: 'Sequelize',
    name: 'Sequelize',
    value: 'Sequelize',
    path: technosPath.sequelize,
  },
  {
    id: 'strapi',
    label: 'Strapi',
    name: 'Strapi',
    value: 'Strapi',
    path: technosPath.strapi,
  },
  {
    id: 'vite',
    label: 'Vite',
    name: 'Vite',
    value: 'Vite',
    path: technosPath.vite,
  },
  {
    id: 'vuejs',
    label: 'Vuejs',
    name: 'Vuejs',
    value: 'Vuejs',
    path: technosPath.vuejs,
  },
];
